# Generated by Django 3.0.5 on 2020-05-14 14:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('content', models.TextField()),
                ('Reqirements', models.TextField()),
                ('type', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='')),
                ('posted_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('level', models.CharField(max_length=100)),
            ],
        ),
    ]
