# Generated by Django 3.0.5 on 2020-05-15 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='logo',
            field=models.ImageField(upload_to='media/logo'),
        ),
    ]
