# Generated by Django 3.0.5 on 2020-05-18 13:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20200518_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='offline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('method', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=1000)),
                ('offered_by', models.CharField(max_length=1000)),
                ('content', models.TextField()),
                ('Reqirements', models.TextField()),
                ('benifits', models.TextField()),
                ('how_to_post', models.TextField()),
                ('posted_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_date', models.DateTimeField()),
                ('logo', models.ImageField(upload_to='logo')),
                ('url', models.CharField(max_length=10000)),
            ],
        ),
    ]
