# Generated by Django 3.0.5 on 2020-05-18 14:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_offline'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='eligibility',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
